import type { RobotLevel } from "./engine";

export type Chapter = {
  id: string;
  emoji: string;
  title: string;
  titleEn: string;
  /** what the concept means in "real" programming */
  concept: string;
  /** the same idea in everyday code */
  code: string;
  levels: RobotLevel[];
};

const E = 1 as const;
const N = 0 as const;

export const CHAPTERS: Chapter[] = [
  {
    id: "seq",
    emoji: "👣",
    title: "ลำดับคำสั่ง",
    titleEn: "Sequence",
    concept: "โปรแกรมคือรายการคำสั่งที่คอมทำทีละบรรทัด จากบนลงล่าง ไม่ข้าม ไม่เดา — สั่งผิดลำดับก็ผิดทาง",
    code: "forward()\nforward()\nturnLeft()\nforward()",
    levels: [
      {
        id: "seq-1",
        title: "ก้าวแรก",
        titleEn: "First Steps",
        intro: "แตะช่องใน F1 แล้วเลือกคำสั่ง ↑ (เดินหน้า) จากนั้นกด ▶ Run ให้หุ่นไปเก็บ ★",
        hints: ["ต้องเดินหน้ากี่ช่องถึงดาว?"],
        board: ["bbbB"],
        start: { x: 0, y: 0, dir: E },
        funcs: [3],
        solution: "F F F",
      },
      {
        id: "seq-2",
        title: "เลี้ยวครั้งแรก",
        titleEn: "First Turn",
        intro: "↺ = หมุนซ้าย, ↻ = หมุนขวา หมุนอยู่กับที่ ไม่เดิน — ลองนึกว่าตัวเองเป็นหุ่นที่หันหน้าไปทางลูกศร",
        hints: ["หุ่นหันไปทางขวา ต้องหมุนไปทางไหนถึงจะหันขึ้นข้างบน?"],
        board: ["..B", "..b", "bbb"],
        start: { x: 0, y: 2, dir: E },
        funcs: [5],
        solution: "F F L F F",
      },
      {
        id: "seq-3",
        title: "ซิกแซก",
        titleEn: "Zigzag",
        intro: "เลี้ยวซ้าย-ขวาสลับกัน ใช้ปุ่ม ⏭ รันทีละคำสั่งเพื่อดูว่าหุ่นทำอะไร",
        hints: ["เขียนทีละก้าว แล้วกด ⏭ ตรวจทีละคำสั่ง"],
        board: ["..bB", ".bb.", "bb.."],
        start: { x: 0, y: 2, dir: E },
        funcs: [9],
        solution: "F L F R F L F R F",
      },
      {
        id: "seq-4",
        title: "เก็บให้ครบ",
        titleEn: "Collect Them All",
        intro: "ดาวมีหลายดวง ต้องเก็บให้ครบทุกดวงถึงจะผ่าน",
        hints: ["ไปเก็บดวงที่ใกล้ก่อน แล้วค่อยไปดวงถัดไป"],
        board: ["Bbbb", "b..b", "b..B"],
        start: { x: 0, y: 2, dir: N },
        funcs: [10],
        solution: "F F R F F F R F F",
      },
      {
        id: "seq-5",
        title: "กลับหลังหัน",
        titleEn: "About Face",
        intro: "ดาวอยู่ทั้งสองฝั่ง! หุ่นหันหลังได้ด้วยการหมุนสองครั้ง",
        hints: ["หมุนซ้าย 2 ครั้ง = หันหลัง"],
        board: ["BbbbB"],
        start: { x: 2, y: 0, dir: E },
        funcs: [8],
        solution: "F F L L F F F F",
      },
    ],
  },
  {
    id: "func",
    emoji: "📦",
    title: "ฟังก์ชัน",
    titleEn: "Functions",
    concept:
      "ฟังก์ชัน = ตั้งชื่อให้ชุดคำสั่ง แล้วเรียกใช้ซ้ำได้ ไม่ต้องเขียนใหม่ทุกครั้ง ปุ่ม F2 ใน F1 คือ \"ไปทำทุกคำสั่งใน F2 แล้วกลับมาทำต่อ\"",
    code: "function walk2() {\n  forward()\n  forward()\n}\nwalk2(); walk2(); walk2()",
    levels: [
      {
        id: "func-1",
        title: "ตั้งชื่อท่า",
        titleEn: "Name a Move",
        intro: "F1 มีแค่ 4 ช่อง แต่ต้องเดิน 8 ก้าว — ใส่ท่า 'เดิน 2 ก้าว' ไว้ใน F2 แล้วให้ F1 เรียก F2 หลายๆ ครั้ง",
        hints: ["F2 = ↑ ↑", "F1 เรียก F2 กี่ครั้งถึงได้ 8 ก้าว?"],
        board: ["bbbbbbbbB"],
        start: { x: 0, y: 0, dir: E },
        funcs: [4, 2],
        solution: "2 2 2 2 | F F",
      },
      {
        id: "func-2",
        title: "มุมฉาก",
        titleEn: "Right Angle",
        intro: "ขาทั้งสองข้างยาวเท่ากัน — เขียนท่า 'เดินหนึ่งขา' ครั้งเดียว ใช้สองรอบ",
        hints: ["F2 = เดินหนึ่งขา (4 ก้าว)", "F1: เดินขา, เลี้ยว, เดินขา"],
        board: ["....B", "....b", "....b", "....b", "bbbbb"],
        start: { x: 0, y: 4, dir: E },
        funcs: [3, 4],
        solution: "2 L 2 | F F F F",
      },
      {
        id: "func-3",
        title: "บันได 4 ขั้น",
        titleEn: "Four Steps",
        intro: "หนึ่งขั้นบันไดคือท่าที่ซ้ำกัน — จับใส่ฟังก์ชัน",
        hints: ["หนึ่งขั้น = เดิน, เลี้ยวซ้าย, เดิน, เลี้ยวขวา"],
        board: ["....B", "...bb", "..Bb.", ".bb..", "bb..."],
        start: { x: 0, y: 4, dir: E },
        funcs: [4, 4],
        solution: "2 2 2 2 | F L F R",
      },
      {
        id: "func-4",
        title: "สองท่า",
        titleEn: "Two Moves",
        intro: "ใช้ 2 ฟังก์ชันสำหรับ 2 ท่าที่ต่างกัน: ด้านยาวกับด้านสั้น",
        hints: ["F2 = ด้านยาว, F3 = ด้านสั้น", "F1: ยาว, เลี้ยว, สั้น, เลี้ยว, ยาว"],
        board: ["Bbbbb", "....b", "bbbbB"],
        start: { x: 0, y: 2, dir: E },
        funcs: [5, 4, 2],
        solution: "2 L 3 L 2 | F F F F | F F",
      },
    ],
  },
  {
    id: "loop",
    emoji: "🔁",
    title: "ลูป",
    titleEn: "Loops",
    concept:
      "ลูป = ทำซ้ำไปเรื่อยๆ ในเกมนี้ ถ้าคำสั่งสุดท้ายของ F1 คือ F1 เอง ก็คือ \"กลับไปเริ่ม F1 ใหม่\" ไม่รู้จบ (หยุดเมื่อเก็บดาวครบ)",
    code: "while (true) {\n  forward()\n}",
    levels: [
      {
        id: "loop-1",
        title: "วนไม่รู้จบ",
        titleEn: "Forever",
        intro: "ทางยาวกว่าช่องคำสั่ง! ใส่ F1 เป็นคำสั่งสุดท้ายของ F1 = วนกลับไปเริ่มใหม่",
        hints: ["มีแค่ 2 ช่อง: เดิน แล้ว...?", "ฟังก์ชันเรียกตัวเองได้"],
        board: ["bbbbbbbbbbbB"],
        start: { x: 0, y: 0, dir: E },
        funcs: [2],
        solution: "F 1",
      },
      {
        id: "loop-2",
        title: "บันไดไม่มีที่สิ้นสุด",
        titleEn: "Endless Stairs",
        intro: "เขียนหนึ่งขั้น แล้ววนซ้ำ",
        hints: ["หนึ่งขั้นใช้ 4 คำสั่ง ช่องที่ 5 ใช้วน"],
        board: [".....B", "....Bb", "...bb.", "..Bb..", ".bb...", "bb...."],
        start: { x: 0, y: 5, dir: E },
        funcs: [5],
        solution: "F L F R 1",
      },
      {
        id: "loop-3",
        title: "ขั้นใหญ่",
        titleEn: "Big Steps",
        intro: "บันไดขั้นละ 2 ช่อง — นับให้ดี",
        hints: ["หนึ่งขั้น: เดิน 2, เลี้ยวซ้าย, เดิน 2, เลี้ยวขวา"],
        board: [
          "........B",
          "........b",
          "......bbb",
          "......b..",
          "....Bbb..",
          "....b....",
          "..bbb....",
          "..b......",
          "bbb......",
        ],
        start: { x: 0, y: 8, dir: E },
        funcs: [7],
        solution: "F F L F F R 1",
      },
      {
        id: "loop-4",
        title: "เดินรอบบ้าน",
        titleEn: "Around the Block",
        intro: "สี่ด้านเหมือนกันหมด = ลูป",
        hints: ["หนึ่งด้าน = เดิน 3 แล้วเลี้ยวซ้าย"],
        board: ["BbbB", "b..b", "b..b", "bbbB"],
        start: { x: 0, y: 3, dir: E },
        funcs: [5],
        solution: "F F F L 1",
      },
    ],
  },
  {
    id: "if",
    emoji: "🚦",
    title: "เงื่อนไข if",
    titleEn: "Conditions",
    concept:
      "if = ทำคำสั่งนี้ \"เฉพาะเมื่อ\" เงื่อนไขเป็นจริง คำสั่งที่มีสีจะทำงานก็ต่อเมื่อหุ่นยืนอยู่บนช่องสีนั้น ถ้าไม่ใช่ก็ข้ามไป",
    code: "while (true) {\n  forward()\n  if (tile == RED) turnLeft()\n}",
    levels: [
      {
        id: "if-1",
        title: "เจอแดงให้เลี้ยว",
        titleEn: "Red Means Turn",
        intro: "แตะสีด้านล่างก่อนเลือกคำสั่ง จะได้คำสั่งที่ทำงานเฉพาะบนช่องสีนั้น",
        hints: ["มีแค่ 3 ช่อง: เดิน, เลี้ยว(ถ้าแดง), วน"],
        board: [".....B", ".....b", ".....b", ".....b", "bbbbbr"],
        start: { x: 0, y: 4, dir: E },
        funcs: [3],
        solution: "F L:r 1",
      },
      {
        id: "if-2",
        title: "ก้นหอย",
        titleEn: "Spiral",
        intro: "แต่ละด้านยาวไม่เท่ากัน แต่ทุกมุมเป็นสีแดง",
        hints: ["หุ่นต้องเลี้ยวทางไหนที่มุม?", "เดิน, เลี้ยวถ้าแดง, วน"],
        board: ["bbbbbbr", "......b", "rbbbr.b", "b...b.B", "b.Bbr.b", "b.....b", "rbbBbbr"],
        start: { x: 0, y: 0, dir: E },
        funcs: [3],
        solution: "F R:r 1",
      },
      {
        id: "if-3",
        title: "สองสัญญาณ",
        titleEn: "Two Signals",
        intro: "if สองอัน: แดงแบบหนึ่ง เขียวอีกแบบ",
        hints: ["แดงเลี้ยวไปทางไหน? เขียวเลี้ยวไปทางไหน?", "เดิน, ซ้ายถ้าแดง, ขวาถ้าเขียว, วน"],
        board: ["...B...", "...gbbr", "......b", "......b", "...gbbr", "...b...", "bbbr..."],
        start: { x: 0, y: 6, dir: E },
        funcs: [4],
        solution: "F L:r R:g 1",
      },
      {
        id: "if-4",
        title: "เขาวงกตสี",
        titleEn: "Color Maze",
        intro: "ทางคดเคี้ยวขึ้น แต่กฎเหมือนเดิม — อ่านกระดานให้ออก",
        hints: ["ดูทิศที่หุ่นเข้ามาที่แต่ละมุม แล้วดูว่าต้องเลี้ยวซ้ายหรือขวา"],
        board: ["bbbg..", "...b..", "...rbg", ".....b", ".rbbBg", ".b....", ".B...."],
        start: { x: 0, y: 0, dir: E },
        funcs: [4],
        solution: "F L:r R:g 1",
      },
      {
        id: "if-5",
        title: "หวีฟันหลอ",
        titleEn: "The Comb",
        intro: "ขึ้นไปเก็บดาวบนยอดแต่ละซี่ แล้วลงมาเดินต่อ",
        hints: [
          "ทางแยกเป็นสีเขียว ยอดเป็นสีแดง",
          "ขาขึ้นที่เขียวต้องเลี้ยวซ้าย ขาลงที่เขียว... ก็เลี้ยวซ้ายเหมือนกัน!",
          "บนยอดแดงต้องกลับหลังหัน",
        ],
        board: [".......R.", ".....R.b.", "..R..b.b.", "..b..b.b.", "bbgbbgbgB"],
        start: { x: 0, y: 4, dir: E },
        funcs: [5],
        solution: "F L:g R:r R:r 1",
      },
    ],
  },
  {
    id: "else",
    emoji: "🔀",
    title: "if / else if",
    titleEn: "Branching",
    concept:
      "ใส่เงื่อนไขให้การเรียกฟังก์ชัน = แยกทางเดินของโปรแกรม ถ้าแดงไปทำท่าหนึ่ง ถ้าเขียวไปทำอีกท่า ถ้าไม่ใช่ทั้งคู่ก็ทำต่อตามปกติ",
    code: "while (true) {\n  forward()\n  if (tile == RED) stepUp()\n  else if (tile == GREEN) stepDown()\n}",
    levels: [
      {
        id: "else-1",
        title: "ขึ้นขั้นเมื่อเจอแดง",
        titleEn: "Step on Red",
        intro: "บันไดที่ไม่สม่ำเสมอ — ขึ้นขั้นเฉพาะตรงช่องแดง",
        hints: ["F2 = ท่าขึ้นหนึ่งขั้น (ซ้าย, เดิน, ขวา)", "F1: เดิน, เรียก F2 ถ้าแดง, วน"],
        board: [".......bB", ".....bbr.", "..bbBr...", "bbr......"],
        start: { x: 0, y: 3, dir: E },
        funcs: [3, 3],
        solution: "F 2:r 1 | L F R",
      },
      {
        id: "else-2",
        title: "ขึ้นหรือลง",
        titleEn: "Up or Down",
        intro: "แดง = ขึ้นขั้น, เขียว = ลงขั้น แยกเป็นสองฟังก์ชัน",
        hints: ["F2 = ขึ้น (ซ้าย เดิน ขวา), F3 = ลง (ขวา เดิน ซ้าย)", "F1: เดิน, F2 ถ้าแดง, F3 ถ้าเขียว, วน"],
        board: [".....bg.", ".bBgbrbB", "br.br..."],
        start: { x: 0, y: 2, dir: E },
        funcs: [4, 3, 3],
        solution: "F 2:r 3:g 1 | L F R | R F L",
      },
      {
        id: "else-3",
        title: "งูเลื้อย",
        titleEn: "Snake",
        intro: "เดินไปกลับทีละแถว ปลายแต่ละข้างต้องเลี้ยวไม่เหมือนกัน",
        hints: [
          "ปลายขวาเป็นสีเขียว ปลายซ้ายเป็นสีแดง",
          "ปลายขวา: ขวา-เดิน-ขวา, ปลายซ้าย: ซ้าย-เดิน-ซ้าย",
        ],
        board: ["bbbbbg", "rbBbbb", "bbbBbg", "rbbbbb", "bbbbbB"],
        start: { x: 0, y: 0, dir: E },
        funcs: [4, 3, 3],
        solution: "F 2:g 3:r 1 | R F R | L F L",
      },
    ],
  },
  {
    id: "nest",
    emoji: "🪆",
    title: "ลูปซ้อนลูป",
    titleEn: "Nested Loops",
    concept: "ลูปข้างในทำงานจนจบก่อน แล้วลูปข้างนอกค่อยขยับไปรอบถัดไป เหมือนเข็มนาทีกับเข็มชั่วโมง",
    code: "while (true) {        // ทุกด้าน\n  repeat(2) walk2()   // เดินหนึ่งด้าน\n  turnLeft()\n}",
    levels: [
      {
        id: "nest-1",
        title: "สี่เหลี่ยมวน",
        titleEn: "The Ring",
        intro: "F2 มีแค่ 2 ช่อง แต่ด้านยาว 4 ช่อง...",
        hints: ["เรียก F2 สองครั้งติดกันได้", "หนึ่งด้าน = F2 F2 เลี้ยว แล้ววน"],
        board: ["BbbbB", "b...b", "B...b", "b...b", "bbbbB"],
        start: { x: 0, y: 4, dir: E },
        funcs: [4, 2],
        solution: "2 2 L 1 | F F",
      },
      {
        id: "nest-2",
        title: "ดาวสี่ทิศ",
        titleEn: "Four Arms",
        intro: "ออกไปเก็บดาวปลายแขนแต่ละข้าง แล้วกลับมาที่กลาง",
        hints: ["ท่าไปกลับหนึ่งแขน: เดิน 2, หันหลัง, เดิน 2", "กลับมาถึงกลางแล้ว หันไปแขนถัดไปยังไง?"],
        board: ["..B..", "..b..", "BbbbB", "..b..", "..B.."],
        start: { x: 2, y: 2, dir: N },
        funcs: [3, 6],
        solution: "2 R 1 | F F L L F F",
      },
      {
        id: "nest-3",
        title: "ฟันเลื่อย",
        titleEn: "Sawtooth",
        intro: "ขึ้นไปยอด ลงมา ขยับ แล้วทำซ้ำ — มีลูปอยู่ 3 ชั้น",
        hints: ["F3 = เดินหนึ่งขา (3 ก้าว)", "F2 = ขึ้นไปแล้วลงมา", "F1 = F2 แล้วขยับไปฟันถัดไป แล้ววน"],
        board: ["B.B.B.B", "b.b.b.b", "b.b.b.b", "bbbbbbb"],
        start: { x: 0, y: 3, dir: N },
        funcs: [6, 4, 3],
        solution: "2 L F F L 1 | 3 L L 3 | F F F",
      },
    ],
  },
  {
    id: "stack",
    emoji: "📚",
    title: "Recursion & Stack",
    titleEn: "Recursion",
    concept:
      "ถ้าฟังก์ชันเรียกตัวเอง \"ตรงกลาง\" (ไม่ใช่คำสั่งสุดท้าย) คำสั่งที่เหลือจะถูกพักไว้ใน stack แล้วทำตอนขากลับ — เรียกลึก N ชั้น ขากลับก็ทำ N ครั้ง",
    code: "function go() {\n  forward()\n  if (tile == BLUE) go()\n  // ทำตอนขากลับ ทุกชั้น\n  forward()\n}",
    levels: [
      {
        id: "stack-1",
        title: "นับถอยหลัง",
        titleEn: "Echo",
        intro: "เดินไปขวาจนเจอแดง แล้วขึ้นไปข้างบนเป็นระยะเท่ากันพอดี — ทางข้างบนยาวเกิน ห้ามเดินเลย",
        hints: [
          "คำสั่งหลังการเรียกตัวเองจะรอทำตอนขากลับ",
          "เรียกตัวเองไป N ชั้น → คำสั่งหลังการเรียกถูกทำ N ครั้ง",
          "ลองโครง: เดิน, เรียกตัวเองถ้าฟ้า, ..., ...",
        ],
        board: ["....b", "....b", "....B", "....b", "....b", "....b", "bbBbr"],
        start: { x: 0, y: 6, dir: E },
        funcs: [4],
        solution: "F 1:b L:r F",
      },
      {
        id: "stack-2",
        title: "มุมกระจก",
        titleEn: "Mirror Corner",
        intro: "ขึ้นไปเท่าไหร่ ไปทางขวาเท่านั้น",
        hints: ["คล้ายด่านที่แล้ว แต่คราวนี้เลี้ยวขวา", "นับจำนวนชั้นด้วย recursion ไม่ใช่ด้วยสี"],
        board: ["rbbbBbbb", "b.......", "b.......", "b.......", "b......."],
        start: { x: 0, y: 4, dir: N },
        funcs: [4],
        solution: "F 1:b R:r F",
      },
      {
        id: "stack-3",
        title: "ไปแล้วกลับ",
        titleEn: "There and Back",
        intro: "ไปเก็บดาวที่ปลายทาง แล้วกลับมาที่จุดเริ่มพอดี ก่อนขึ้นไปเก็บดาวดวงสุดท้าย",
        hints: [
          "F2 เดินไปจนสุดทาง (recursion) — ที่ปลายแดงให้หันหลัง",
          "ขากลับ แต่ละชั้นเดิน 1 ก้าว → กลับถึงจุดเริ่มพอดี",
          "F1 เรียก F2 แล้วค่อยเลี้ยวขึ้นไปเก็บดาว",
        ],
        board: ["...B....", "bbbbbbbR"],
        start: { x: 3, y: 1, dir: E },
        funcs: [3, 5],
        solution: "2 R F | F 2:b L:r L:r F",
      },
    ],
  },
  {
    id: "debug",
    emoji: "🐞",
    title: "Debug",
    titleEn: "Find the Bug",
    concept:
      "โปรแกรมเมอร์ใช้เวลาหาบั๊กมากกว่าเขียนโค้ดใหม่ ด่านนี้มีโปรแกรมมาให้แล้ว แต่มีจุดผิด — รันดูก่อน สังเกตว่าพังตรงไหน แล้วแก้ให้น้อยที่สุด",
    code: "// expected: turnLeft()\nturnRight()  // ← bug!",
    levels: [
      {
        id: "debug-1",
        title: "เลี้ยวผิดข้าง",
        titleEn: "Wrong Turn",
        intro: "โปรแกรมนี้เกือบถูกแล้ว กด Run ดูว่าหุ่นพลาดตรงไหน",
        hints: ["หุ่นตกตอนไหน? คำสั่งก่อนหน้านั้นคืออะไร?"],
        board: ["....B", "....b", "....b", "....b", "bbbbb"],
        start: { x: 0, y: 4, dir: E },
        funcs: [3, 4],
        solution: "2 L 2 | F F F F",
        preset: "2 R 2 | F F F F",
      },
      {
        id: "debug-2",
        title: "สีสลับ",
        titleEn: "Swapped Colors",
        intro: "มีคนใส่เงื่อนไขสีผิด ลองรันทีละคำสั่ง (⏭)",
        hints: ["ที่ช่องแดง หุ่นควรเลี้ยวไปทางไหน?"],
        board: ["...B...", "...gbbr", "......b", "......b", "...gbbr", "...b...", "bbbr..."],
        start: { x: 0, y: 6, dir: E },
        funcs: [4],
        solution: "F L:r R:g 1",
        preset: "F L:g R:r 1",
      },
      {
        id: "debug-3",
        title: "ลืมอะไรไป?",
        titleEn: "Something Missing",
        intro: "หุ่นทำงานได้ฟันเดียวแล้วหยุด ทำไมนะ?",
        hints: ["โปรแกรมจบเอง แปลว่าไม่มีอะไรสั่งให้ทำซ้ำ"],
        board: ["B.B.B.B", "b.b.b.b", "b.b.b.b", "bbbbbbb"],
        start: { x: 0, y: 3, dir: N },
        funcs: [6, 4, 3],
        solution: "2 L F F L 1 | 3 L L 3 | F F F",
        preset: "2 L F F L | 3 L L 3 | F F F",
      },
      {
        id: "debug-4",
        title: "ลำดับพัง",
        titleEn: "Out of Order",
        intro: "คำสั่งครบทุกตัว แต่ลำดับผิด — หุ่นไม่ยอมขึ้นบันไดเลย",
        hints: ["การเรียก F1 ควรอยู่ตรงไหนของ F1?", "ถ้าเรียกตัวเองก่อน คำสั่งที่เหลือจะไม่เคยได้ทำเลย"],
        board: [".......bB", ".....bbr.", "..bbBr...", "bbr......"],
        start: { x: 0, y: 3, dir: E },
        funcs: [3, 3],
        solution: "F 2:r 1 | L F R",
        preset: "F 1 2:r | L F R",
      },
    ],
  },
];

export const ROBOT_LEVELS: RobotLevel[] = CHAPTERS.flatMap((c) => c.levels);

export const chapterOf = (levelId: string) => CHAPTERS.find((c) => c.levels.some((l) => l.id === levelId));

export const robotLevel = (id: string) => ROBOT_LEVELS.find((l) => l.id === id);
