// Builds the Harbor puzzle bank: `npx tsx scripts/build-harbor.ts`
// Deep Rush Hour layouts take too long to search for on a phone, so they're found once here.
import { writeFileSync } from "node:fs";
import { HARBOR_LEVELS, encodeHarbor, generateHarbor, type HarborLevel } from "../src/games/harbor/logic";
import { rngFrom } from "../src/lib/rng";

const PER_LEVEL = 150;
const out: Record<string, string[]> = {};
for (const level of Object.keys(HARBOR_LEVELS) as HarborLevel[]) {
  const seen = new Set<string>();
  for (let i = 0; seen.size < PER_LEVEL; i++) seen.add(encodeHarbor(generateHarbor(rngFrom(`harbor-bank:${level}:${i}`), level)));
  out[level] = [...seen];
  console.log(level, out[level].length);
}
writeFileSync(
  "src/games/harbor/bank.ts",
  `// Generated by scripts/build-harbor.ts — do not edit by hand.\n// Each entry: boats as <len><h|v><lane><pos>, ship first, then |par.\nexport const HARBOR_BANK: Record<string, string[]> = ${JSON.stringify(out, null, 1)};\n`,
);
